python score_imagenet_loss.py --epoch 1 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 2 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 3 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 4 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 5 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 6 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 7 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 8 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 9 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 10 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 11 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 12 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 13 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 14 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 15 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 16 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 17 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 18 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 19 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 20 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 21 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 22 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 23 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 24 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 25 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 26 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 27 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 28 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 29 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 30 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 31 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 32 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 33 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 34 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 35 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 36 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 37 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 38 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 39 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 40 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 41 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 42 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 43 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 44 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 45 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 46 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 47 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 48 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 49 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 50 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 51 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 52 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 53 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 54 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 55 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 56 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 57 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 58 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 59 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 60 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 61 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 62 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 63 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 64 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 65 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 66 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 67 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 68 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 69 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 70 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 71 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 72 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 73 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 74 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 75 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 76 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 77 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 78 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 79 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 80 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 81 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 82 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 83 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 84 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 85 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 86 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 87 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 88 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 89 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 90 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 91 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 92 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 93 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 94 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 95 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 96 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 97 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 98 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 99 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 100 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 101 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 102 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 103 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 104 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 105 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 106 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 107 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 108 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 109 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 110 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 111 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 112 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 113 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 114 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 115 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 116 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 117 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 118 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 119 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 120 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 121 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 122 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 123 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 124 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 125 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 126 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 127 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 128 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 129 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 130 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 131 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 132 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 133 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 134 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 135 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 136 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 137 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 138 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 139 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 140 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 141 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 142 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 143 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 144 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 145 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 146 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 147 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 148 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 149 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 150 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 151 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 152 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 153 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 154 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 155 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 156 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 157 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 158 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 159 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 160 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 161 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 162 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 163 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 164 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 165 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 166 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 167 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 168 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 169 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 170 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 171 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 172 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 173 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 174 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 175 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 176 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 177 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 178 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 179 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 180 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 181 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 182 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 183 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 184 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 185 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 186 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 187 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 188 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 189 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 190 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 191 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 192 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 193 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 194 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 195 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 196 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 197 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 198 --parallel f --train_batch_size 128 --test_batch_size 128
python score_imagenet_loss.py --epoch 199 --parallel f --train_batch_size 128 --test_batch_size 128
